[package]
authors = ["Kasun Ranasingge <kasunranasinghe303@gmail.com>"]
description = "A high-level LDAP client for Rust"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/keaz/simple-ldap"
keywords = ["ldap", "ldap3", "async", "high-level"]
name = "simple-ldap"
version = "3.0.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool = { version = "0.12.1", optional = true}
futures = "0.3.31"
ldap3 = { version = "0.11.5", default-features = false }
serde = { version = "1.0.214", features = ["derive"] }
serde-value = "0.7.0"
serde_json = "1.0.132"
thiserror = "2.0.2"
tracing = "0.1.41"
url = "2.5.4"

[dev-dependencies]
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }

[features]
default = ["ldap3/default"]
tls = ["ldap3/tls"]
tls-native = ["ldap3/tls-native"]
tls-rustls = ["ldap3/tls-rustls"]
gssapi = ["ldap3/gssapi"]
sync = ["ldap3/sync"]
pool = ["dep:deadpool"]
