[package]
authors = ["Kasun Ranasingge <kasunranasinghe303@gmail.com>"]
description = "Simple LDAP client for Rust"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/keaz/simple-ldap"
keywords = ["ldap", "client", "ldap3", "async","simple"]
name = "simple-ldap"
version = "0.0.4"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ldap3 = "0.11.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
