[package]
authors = ["Kasun Ranasingge <kasunranasinghe303@gmail.com>"]
description = "A high-level LDAP client for Rust"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/keaz/simple-ldap"
keywords = ["ldap", "ldap3", "async", "high-level"]
name = "simple-ldap"
version = "1.5.1"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.75"
deadpool = "0.10.0"
ldap3 = { version = "0.11.3", default-features = false }
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

[features]
default = ["ldap3/default"]
tls = ["ldap3/tls"]
tls-native = ["ldap3/tls-native"]
tls-rustls = ["ldap3/tls-rustls"]
gssapi = ["ldap3/gssapi"]
sync = ["ldap3/sync"]

[lib]
doctest = false
